import { StyleSheet } from "react-native";

export const authStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0A0F1D" },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  logoContainer: { alignItems: "center", marginBottom: 30 },
  logoBox: {
    width: 64,
    height: 64,
    borderRadius: 16,
    backgroundColor: "#1B2A4A",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(52, 199, 89, 0.4)",
    marginBottom: 16,
  },
  appName: {
    color: "#FFFFFF",
    fontSize: 26,
    fontWeight: "bold",
    marginBottom: 6,
  },
  appSubtitle: { color: "#8E8E93", fontSize: 14 },
  card: {
    backgroundColor: "#1B2A4A",
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  welcomeText: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 20,
  },
  inputContainer: { marginBottom: 16 },
  inputLabel: { color: "#8E8E93", fontSize: 13, marginBottom: 8 },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0A0F1D",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    paddingHorizontal: 14,
    height: 50,
  },
  inputIcon: { marginRight: 10 },
  input: { flex: 1, color: "#FFFFFF", fontSize: 15 },
  mainButton: {
    backgroundColor: "#34C759",
    height: 50,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 20,
  },
  mainButtonText: { color: "#0A0F1D", fontSize: 16, fontWeight: "bold" },
  footerRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  footerText: { color: "#8E8E93", fontSize: 14 },
  linkText: { color: "#34C759", fontSize: 14, fontWeight: "bold" },
});
