import { StyleSheet } from 'react-native';

export const coinDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0A0F1D",
  },
  loaderContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  headerBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#1B2A4A",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "bold",
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 20,
  },
  priceContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  currentPrice: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "bold",
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  changeText: {
    fontSize: 14,
    fontWeight: "600",
  },
  chartCard: {
    backgroundColor: "#1B2A4A",
    borderRadius: 20,
    padding: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  chartContainer: {
    height: 160,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  timeframeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  timeframeButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  activeTimeframeButton: {
    backgroundColor: "rgba(52, 199, 89, 0.2)",
  },
  timeframeText: {
    color: "#8E8E93",
    fontSize: 13,
    fontWeight: "600",
  },
  activeTimeframeText: {
    color: "#34C759",
  },
  sectionTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 12,
  },
  statsCard: {
    backgroundColor: "#1B2A4A",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  statRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.05)",
  },
  statLabel: {
    color: "#8E8E93",
    fontSize: 14,
  },
  statValue: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  footerActionRow: {
    flexDirection: "row",
    padding: 16,
    backgroundColor: "#0A0F1D",
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.08)",
    gap: 12,
  },
  sellButton: {
    flex: 1,
    backgroundColor: "rgba(255, 69, 58, 0.15)",
    height: 50,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 69, 58, 0.3)",
  },
  sellButtonText: {
    color: "#FF453A",
    fontSize: 16,
    fontWeight: "bold",
  },
  buyButton: {
    flex: 1,
    backgroundColor: "#34C759",
    height: 50,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  buyButtonText: {
    color: "#0A0F1D",
    fontSize: 16,
    fontWeight: "bold",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#1B2A4A",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.1)",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  modalTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "bold",
  },
  modalSubtitle: {
    color: "#8E8E93",
    fontSize: 14,
    marginBottom: 20,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0A0F1D",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    paddingHorizontal: 16,
    height: 54,
    marginBottom: 24,
  },
  currencySymbol: {
    color: "#34C759",
    fontSize: 20,
    fontWeight: "bold",
    marginRight: 8,
  },
  modalInput: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "bold",
  },
  actionButton: {
    height: 50,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  actionButtonText: {
    fontSize: 16,
    fontWeight: "bold",
  },
});