import { StyleSheet } from "react-native";

export const portfolioStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0A0F1D" },
  scrollContent: { paddingHorizontal: 16, paddingTop: 10, paddingBottom: 30 },
  screenTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 16,
  },
  portfolioCard: {
    backgroundColor: "#1B2A4A",
    borderRadius: 20,
    padding: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  cardTitle: { color: "#8E8E93", fontSize: 14, marginBottom: 6 },
  totalBalance: {
    color: "#FFFFFF",
    fontSize: 32,
    fontWeight: "bold",
    marginBottom: 8,
  },
  profitRow: { flexDirection: "row", alignItems: "center" },
  profitText: { color: "#34C759", fontSize: 14, fontWeight: "600" },
  sectionTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 12,
  },
  assetItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#1B2A4A",
    padding: 14,
    borderRadius: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  assetLeft: { flexDirection: "row", alignItems: "center", gap: 12 },
  iconBox: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  iconText: { color: "#FFFFFF", fontWeight: "bold", fontSize: 16 },
  assetName: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 2,
  },
  assetAmount: { color: "#8E8E93", fontSize: 13 },
  assetRight: { alignItems: "flex-end" },
  assetValue: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 4,
  },
  assetChange: { fontSize: 12, fontWeight: "600" },
});
