import { StyleSheet } from "react-native";

export const settingStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0A0F1D" },
  scrollContent: { paddingHorizontal: 16, paddingTop: 10, paddingBottom: 30 },
  screenTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 16,
  },
  profileCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1B2A4A",
    padding: 16,
    borderRadius: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    gap: 16,
  },
  avatarBox: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#34C759",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: { color: "#0A0F1D", fontSize: 18, fontWeight: "bold" },
  profileName: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 2,
  },
  profileEmail: { color: "#8E8E93", fontSize: 13 },
  groupTitle: {
    color: "#8E8E93",
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 8,
    marginLeft: 4,
  },
  groupContainer: {
    backgroundColor: "#1B2A4A",
    borderRadius: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    overflow: "hidden",
  },
  rowItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.05)",
  },
  rowLeft: { flexDirection: "row", alignItems: "center", gap: 12 },
  rowText: { color: "#FFFFFF", fontSize: 15, fontWeight: "500" },
  logoutButton: {
    backgroundColor: "rgba(255, 69, 58, 0.15)",
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 69, 58, 0.3)",
    marginTop: 10,
  },
  logoutText: { color: "#FF453A", fontSize: 16, fontWeight: "bold" },
});
